var Monday =[['Mozzarella Caprese', 'Pea Falafel'],['Rare Roast Beef','Oaxacan Torta'],['Tuna'],['Turkey Tower', 'Chicken Caesar']];
var MondayDist=[20,20,10,50];
var Tuesday =[ ['ALT', 'Portobello Mushroom'],['Shredded Sirloin Banh MI','Ham & Brie'],['Tuna'],['Smoked Turkey', 'Buffalo Chicken']];
var TuesdayDist=[20,20,10,50];
var Wednesday =[ ['Roasted Asparagus', 'Vegelicious'],['Grilled Sliced Sirloin','Brooklyn Pastrami','Godfather'],['Tuna'],['Special Turkey', 'Bangkok Chicken']];
var WednesdayDist=[20,20,10,50];
var Thursday =[ ['Southwest Veggie','Pea Falafel'],['Corned Beef', 'B.A.T'],['Tuna'],['Turkey Tower', 'Souther Fried Chicken Breast']];
var ThursdayDist=[20,20,10,50];
var Friday =[ ['Focaccia'],['Godfather','Cubano'],['Tuna Club','Lobster Roll'],['Turkey & Apple Salad', 'Grilled Breast Chicken']];
var FridayDist=[10,20,30,40];
var Week=[Monday,Tuesday];
var midEastern=["Chicken Kebobs", "Beef Kebobs", " Shrimp Kebobs", "Vegetable Kebobs", "Israeli Cous Cous","Grilled Vegetables","Cucumber and Chick Pea Salad", "Humus & Chips", "Slice Fruits"]
var midEasternPlat=[1,1,1,1,0,0,0,0,0];
var midEasternDist =[100,100,100,100,50,50,50,75,75];
var dispName=["Disp", "TIN"];
var ceramicName=["Ceramic", "Metal"];